import { ALERT_EVENT_TYPES, ALERT_STATUSES, DATA_ORIGINS, RULE_KINDS, RULE_SCOPES, SEVERITIES } from '@aer/domain';
import { boolean, integer, jsonb, numeric, pgTable, text, uuid } from 'drizzle-orm/pg-core';
import { createdAtColumn, tz, updatedAtColumn } from './columns';

export const detectionRules = pgTable('detection_rules', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  kind: text('kind', { enum: RULE_KINDS }).notNull(),
  scopeType: text('scope_type', { enum: RULE_SCOPES }).notNull(),
  sectorId: uuid('sector_id'),
  deviceId: uuid('device_id'),
  params: jsonb('params').$type<Record<string, unknown>>().notNull().default({}),
  windowSeconds: integer('window_seconds').notNull(),
  minDurationSeconds: integer('min_duration_seconds').notNull(),
  minCoverageRatio: numeric('min_coverage_ratio', { precision: 4, scale: 3 }).notNull(),
  severity: text('severity', { enum: SEVERITIES }).notNull(),
  suppressionSeconds: integer('suppression_seconds').notNull().default(3600),
  recoverySeconds: integer('recovery_seconds').notNull().default(600),
  respectSupplySchedule: boolean('respect_supply_schedule').notNull().default(true),
  respectMaintenance: boolean('respect_maintenance').notNull().default(true),
  isEnabled: boolean('is_enabled').notNull().default(true),
  createdBy: uuid('created_by'),
  archivedAt: tz('archived_at'),
  createdAt: createdAtColumn(),
  updatedAt: updatedAtColumn(),
});

export const alerts = pgTable('alerts', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  ruleId: uuid('rule_id').notNull(),
  sectorId: uuid('sector_id'),
  deviceId: uuid('device_id'),
  dedupKey: text('dedup_key').notNull(),
  status: text('status', { enum: ALERT_STATUSES }).notNull().default('OPEN'),
  severity: text('severity', { enum: SEVERITIES }).notNull(),
  title: text('title').notNull(),
  priorityScore: integer('priority_score').notNull().default(0),
  evidence: jsonb('evidence').$type<Record<string, unknown>>().notNull(),
  occurrences: integer('occurrences').notNull().default(1),
  firstDetectedAt: tz('first_detected_at').notNull(),
  lastDetectedAt: tz('last_detected_at').notNull(),
  recoveryObservedAt: tz('recovery_observed_at'),
  acknowledgedAt: tz('acknowledged_at'),
  acknowledgedBy: uuid('acknowledged_by'),
  investigationStartedAt: tz('investigation_started_at'),
  resolvedAt: tz('resolved_at'),
  resolvedBy: uuid('resolved_by'),
  dismissedAt: tz('dismissed_at'),
  dismissedBy: uuid('dismissed_by'),
  dismissalReason: text('dismissal_reason'),
  origin: text('origin', { enum: DATA_ORIGINS }).notNull(),
  simulationRunId: uuid('simulation_run_id'),
  createdAt: createdAtColumn(),
  updatedAt: updatedAtColumn(),
});

export const alertEvents = pgTable('alert_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  alertId: uuid('alert_id').notNull(),
  eventType: text('event_type', { enum: ALERT_EVENT_TYPES }).notNull(),
  fromStatus: text('from_status', { enum: ALERT_STATUSES }),
  toStatus: text('to_status', { enum: ALERT_STATUSES }),
  actorUserId: uuid('actor_user_id'),
  note: text('note'),
  data: jsonb('data').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: createdAtColumn(),
});
