import {
  ATTACHMENT_CONTENT_TYPES,
  DATA_ORIGINS,
  WORK_ORDER_DIAGNOSES,
  WORK_ORDER_EVENT_TYPES,
  WORK_ORDER_PRIORITIES,
  WORK_ORDER_STATUSES,
} from '@aer/domain';
import { bigint, integer, jsonb, numeric, pgTable, real, text, uuid } from 'drizzle-orm/pg-core';
import { createdAtColumn, geometryColumn, tz, updatedAtColumn } from './columns';

export const workOrders = pgTable('work_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  number: bigint('number', { mode: 'number' }).generatedAlwaysAsIdentity().notNull(),
  alertId: uuid('alert_id'),
  sectorId: uuid('sector_id'),
  assetId: uuid('asset_id'),
  deviceId: uuid('device_id'),
  title: text('title').notNull(),
  description: text('description'),
  priority: text('priority', { enum: WORK_ORDER_PRIORITIES }).notNull().default('MEDIUM'),
  status: text('status', { enum: WORK_ORDER_STATUSES }).notNull().default('OPEN'),
  assignedTo: uuid('assigned_to'),
  createdBy: uuid('created_by').notNull(),
  dueAt: tz('due_at'),
  assignedAt: tz('assigned_at'),
  inspectionStartedAt: tz('inspection_started_at'),
  completedAt: tz('completed_at'),
  cancelledAt: tz('cancelled_at'),
  cancellationReason: text('cancellation_reason'),
  diagnosis: text('diagnosis', { enum: WORK_ORDER_DIAGNOSES }),
  inspectionNotes: text('inspection_notes'),
  repairNotes: text('repair_notes'),
  repairedAt: tz('repaired_at'),
  location: geometryColumn('location', 'geometry(Point,4326)'),
  locationAccuracyM: real('location_accuracy_m'),
  estimatedVolumeM3: numeric('estimated_volume_m3', { precision: 12, scale: 3 }),
  version: integer('version').notNull().default(1),
  origin: text('origin', { enum: DATA_ORIGINS }).notNull().default('REAL'),
  simulationRunId: uuid('simulation_run_id'),
  archivedAt: tz('archived_at'),
  createdAt: createdAtColumn(),
  updatedAt: updatedAtColumn(),
});

export const workOrderEvents = pgTable('work_order_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  workOrderId: uuid('work_order_id').notNull(),
  eventType: text('event_type', { enum: WORK_ORDER_EVENT_TYPES }).notNull(),
  fromStatus: text('from_status', { enum: WORK_ORDER_STATUSES }),
  toStatus: text('to_status', { enum: WORK_ORDER_STATUSES }),
  actorUserId: uuid('actor_user_id'),
  data: jsonb('data').$type<Record<string, unknown>>().notNull().default({}),
  clientMutationId: text('client_mutation_id'),
  createdAt: createdAtColumn(),
});

export const attachments = pgTable('attachments', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  workOrderId: uuid('work_order_id').notNull(),
  uploadedBy: uuid('uploaded_by').notNull(),
  storageKey: text('storage_key').notNull(),
  originalFilename: text('original_filename'),
  contentType: text('content_type', { enum: ATTACHMENT_CONTENT_TYPES }).notNull(),
  sizeBytes: integer('size_bytes').notNull(),
  sha256: text('sha256').notNull(),
  capturedAt: tz('captured_at'),
  location: geometryColumn('location', 'geometry(Point,4326)'),
  clientMutationId: text('client_mutation_id'),
  archivedAt: tz('archived_at'),
  createdAt: createdAtColumn(),
});
